create extension if not exists "pgcrypto";
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.folders (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, icon text default '📁', color text default '#8b5cf6', position integer default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.notes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, folder_id uuid references public.folders(id) on delete set null, title text not null default '', color text, content jsonb not null default '{"type":"doc","content":[{"type":"paragraph"}]}'::jsonb, content_text text not null default '', is_favorite boolean not null default false, is_pinned boolean not null default false, is_archived boolean not null default false, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
alter table public.notes add column if not exists color text;
create index if not exists folders_user_position_idx on public.folders(user_id, position); create index if not exists notes_user_updated_idx on public.notes(user_id, updated_at desc); create index if not exists notes_user_deleted_idx on public.notes(user_id, deleted_at); create index if not exists notes_search_idx on public.notes using gin (to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(content_text,'')));
alter table public.profiles enable row level security; alter table public.folders enable row level security; alter table public.notes enable row level security;
drop policy if exists "profiles own rows" on public.profiles;
drop policy if exists "folders own rows" on public.folders;
drop policy if exists "notes own rows" on public.notes;
create policy "profiles own rows" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "folders own rows" on public.folders for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "notes own rows" on public.notes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
grant select, insert, update, delete on table public.profiles, public.folders, public.notes to authenticated;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles (id, name) values (new.id, coalesce(new.raw_user_meta_data->>'name', new.email)); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists profiles_set_updated_at on public.profiles;
drop trigger if exists folders_set_updated_at on public.folders;
drop trigger if exists notes_set_updated_at on public.notes;
create trigger profiles_set_updated_at before update on public.profiles for each row execute procedure public.set_updated_at();
create trigger folders_set_updated_at before update on public.folders for each row execute procedure public.set_updated_at();
create trigger notes_set_updated_at before update on public.notes for each row execute procedure public.set_updated_at();
